### ISSUE TITLE
Max Consecutive Ones

### ISSUE THREAD

**Issue by nemogpt** [jiitopticachapter/Data-Structures-Algo#14]
https://leetcode.com/problems/max-consecutive-ones/

**Comment by vivek-dhiman** [comment]
I will work on this, please assign this to me.
@Naman-Gupta-06

**Comment by Koku-18** [comment]
hey @Naman-Gupta-06 I can work on this. Can you assign this to me?

**Comment by nemogpt** [comment]
you all can work on this . I will be choosing the best one!
Thankyou.
