### ISSUE TITLE
Flattening a Linked List

### ISSUE THREAD

**Issue by nemogpt** [jiitopticachapter/Data-Structures-Algo#8]
https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1

**Comment by rakshitgondwal** [comment]
I can work on this issue.

**Comment by scientific-yash** [comment]
Please assign this issue to me . I really want to contribute. Thank You..

**Comment by krushnadurole** [comment]
please assign this issue to me . i can work on this
